### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by beshoo** [ski7777/gomultiwa#6]
```
[RANK]root:[/whatsapp/gomultiwa]AwesomeBuild
prepare-output
install-packr
build
>>> go build -o output/gomultiwa cmd/gomultiwa/main.go

cmd/gomultiwa/main.go:8:2: cannot find package "github.com/akamensky/argparse" in any of:
        /usr/local/go/src/github.com/akamensky/argparse (from $GOROOT)
        /root/go/src/github.com/akamensky/argparse (from $GOPATH)
cmd/gomultiwa/main.go:9:2: cannot find package "github.com/ski7777/gomultiwa/internal/gomultiwa" in any of:
        /usr/local/go/src/github.com/ski7777/gomultiwa/internal/gomultiwa (from $GOROOT)
        /root/go/src/github.com/ski7777/gomultiwa/internal/gomultiwa (from $GOPATH)

```

**Comment by beshoo** [comment]
I did this 
```
go get github.com/ski7777/gomultiwa
go: finding github.com/ski7777/gomultiwa latest
go: downloading github.com/ski7777/gomultiwa v0.0.0-20191120101946-1599866f48c5
go: extracting github.com/ski7777/gomultiwa v0.0.0-20191120101946-1599866f48c5

```

then i got this 
```

[RANK]root:[/root/go/src/github.com/ski7777/gomultiwa]AwesomeBuild
prepare-output
install-packr
build
>>> cd cmd/gomultiwa; GO111MODULE=on packr2

Error: go.mod is malformed
Usage:
  packr2 [flags]
  packr2 [command]

Available Commands:
  build       Wraps the go build command with packr
  clean       removes any *-packr.go files
  fix         will attempt to fix a application's API to match packr version v2.7.1
  help        Help about any command
  install     Don't. ru
  version     shows packr version

Flags:
  -h, --help               help for packr2
      --ignore-imports     when set to true packr won't resolve imports for boxes
      --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
      --silent             silences all output
      --store-cmd string   sub command to use for packing
  -v, --verbose            enables verbose logging

Use "packr2 [command] --help" for more information about a command.
[RANK]root:[/root/go/src/github.com/ski7777/gomultiwa]

```

**Comment by beshoo** [comment]
@ski7777 dear, i can not even install the lib.
Please may you advise. 

Regard

**Comment by beshoo** [comment]
@ski7777 any advice please?

**Comment by rizalgunawan** [comment]
> I did this
> 
> ```
> go get github.com/ski7777/gomultiwa
> go: finding github.com/ski7777/gomultiwa latest
> go: downloading github.com/ski7777/gomultiwa v0.0.0-20191120101946-1599866f48c5
> go: extracting github.com/ski7777/gomultiwa v0.0.0-20191120101946-1599866f48c5
> ```
> 
> then i got this
> 
> ```
> 
> [RANK]root:[/root/go/src/github.com/ski7777/gomultiwa]AwesomeBuild
> prepare-output
> install-packr
> build
> >>> cd cmd/gomultiwa; GO111MODULE=on packr2
> 
> Error: go.mod is malformed
> Usage:
>   packr2 [flags]
>   packr2 [command]
> 
> Available Commands:
>   build       Wraps the go build command with packr
>   clean       removes any *-packr.go files
>   fix         will attempt to fix a application's API to match packr version v2.7.1
>   help        Help about any command
>   install     Don't. ru
>   version     shows packr version
> 
> Flags:
>   -h, --help               help for packr2
>       --ignore-imports     when set to true packr won't resolve imports for boxes
>       --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
>       --silent             silences all output
>       --store-cmd string   sub command to use for packing
>   -v, --verbose            enables verbose logging
> 
> Use "packr2 [command] --help" for more information about a command.
> [RANK]root:[/root/go/src/github.com/ski7777/gomultiwa]
> ```

I am facing the same issue, I fixed it by running this command 
`cd gomultiwa`
`go mod init`

**Comment by beshoo** [comment]
@rizalgunawan Thank you so much, I am not sure why this poor of documentation.
Well, after installation complete how can we start this! it has to be some file to be called!
Please advise since the dev is busy!

**Comment by beshoo** [comment]
@rizalgunawan I think I figured out how to create users as admin - I will make a full FAQ

**Comment by rizalgunawan** [comment]
Yes you are right, the documentation is still very bad.
After analyzing the code, finally I was able to run it.
What am I doing :

**1. Run the executable file:** `./output/gomultiwa`, you will see this screen
![Start](https://user-images.githubusercontent.com/47345705/72229956-e50ef600-35e4-11ea-8344-3145c1ec5845.png)

**2. Create a new user,** `user new` then follow the instructions
![create user](https://user-images.githubusercontent.com/47345705/72229992-3323f980-35e5-11ea-8bd6-209d30518893.png)

**3. Create a new client**, `client new`, then follow the instructions until the QR code appears
![QR](https://user-images.githubusercontent.com/47345705/72229947-bf81ec80-35e4-11ea-9e16-2546eba1f49a.png)


Hope this help you :)

**Comment by beshoo** [comment]
> Yes you are right, the documentation is still very bad.
> After analyzing the code, finally I was able to run it.
> What am I doing :
> 
> **1. Run the executable file:** `./output/gomultiwa`, you will see this screen
> ![Start](https://user-images.githubusercontent.com/47345705/72229956-e50ef600-35e4-11ea-8344-3145c1ec5845.png)
> 
> **2. Create a new user,** `user new` then follow the instructions
> ![create user](https://user-images.githubusercontent.com/47345705/72229992-3323f980-35e5-11ea-8bd6-209d30518893.png)
> 
> **3. Create a new client**, `client new`, then follow the instructions until the QR code appears
> ![QR](https://user-images.githubusercontent.com/47345705/72229947-bf81ec80-35e4-11ea-9e16-2546eba1f49a.png)
> 
> Hope this help you :)

Thanks so much, yes as l told you l analyse the code, my problem lm php dev am very new to the golang, but to be honest, the script is completely helpful, just small tewks and it is ready for deployment. 

Are you golang expert? I have a problem how to make messages readed on the handler, l found a code from the base lib but l am not sure how to pass ws conn to the read function.

**Comment by arioki1** [comment]
@rizalgunawan how do you solve this problem?

**Comment by rizalgunawan** [comment]
@arioki1 what is your problem?

have you tried this way?
https://github.com/ski7777/gomultiwa/issues/6#issuecomment-570573443
