### ISSUE TITLE
Is this project stll maintained? 

### ISSUE THREAD

**Issue by beshoo** [ski7777/gomultiwa#9]
Dear @ski7777
I am super fan of this project, i can see big future. 
But the response to the issues is almost 0%.

And the documents is not clear nor complete. 
I had instalation problems. 

I go to the #golang on IRC, EVEN the pro can not solve the paker problems and thy ask me to contain the developer. 😁

I am very exited to works with the minimum function 

Send / receive text
Login via multiple accounts 
Use proxy
And please add connection time out parameter, since on the base lib 5 seconds is not enough.

Making it as an get/post parameter is more suitable. 

I would like to see this project a live ASAP. 

Regard

**Comment by ski7777** [comment]
Sorry for my bad response behavior. I am still a student and I am preparing my final exams. This is just a hobby project where I put as much effort in to develop new features. Sadly there is no much time left for community support. I hope this will improve.

Regards
Raphael

**Comment by beshoo** [comment]
The problem is the documentation is relly poor, i can not even install the
lib, since there is a problem with the installer.

I add a post in the git talking about the problem.

More over there is no program to read messages.

Only send.

Regard
